### ISSUE TITLE
Extracting GTK--theme icons stalls

### ISSUE THREAD

**Issue by LallyNZ** [JaKooLit/GTK-themes-icons#1]
Firstly, thanks for sharing your Hyprland configs, they're great!

Not sure if this is an issue on my end or not, but when running the installation scripts the GTK icon extraction process stalls at "Tokyonight-Dark\Actions\24x02" in terminal, had this run for approx. an hour last night before killing the script. Any idea on why this may be occurring?

Can complete the complete install if I choose not to install the GTK Themes but would like to do so to experience the theme as intended.

Running OpenSUSE-Tumbleweed, Hyprland (obviously) and kick the install off after cloning your OpenSUSE-Hyperland git.

**Comment by JaKooLit** [comment]
hi... did the changes 8 hrs ago.. and switched to zip

can you try again? but delete first the contents of ~/.icons or atleast the two tokyonight dark and light icons

**Comment by LallyNZ** [comment]
Yep, great stuff, worked flawlessly! Thanks a lot.
